Repository pampacare/dogs-service, pull requests merged in 2021-10, with the labels that each got.

#5 fix: arrumando as cagadas
  package.json
  prisma/schema.prisma
  src/app.ts
  src/controllers/dogs/CreateDogController.test.ts
  src/controllers/dogs/CreateDogController.ts
  src/controllers/owners/CreateOwnerController.test.ts
  src/controllers/owners/CreateOwnerController.ts
  src/controllers/owners/UpdateAddresOwner.test.ts
  src/controllers/owners/UpdateAddresOwnerController.ts
  src/helpers/sendPushNotifications.ts
  src/protocols/Controller.ts
  src/protocols/index.ts
  yarn.lock
Labels: bug

#6 fix: nada de errado
  src/controllers/dogs/CreateDogController.test.ts
Labels: bug

#7 Test/test for create owner
  prisma/schema.prisma
  src/controllers/owners/CreateOwner.test.ts
  src/controllers/owners/CreateOwnerController.ts
Labels: good first issue

#8 Feature/list owners
  src/controllers/dogs/index.ts
  src/controllers/index.ts
  src/controllers/owners/ListOwnersController.ts
  src/controllers/owners/index.ts
  src/routes/owner.routes.ts
Labels: enhancement
