Repository pampacare/dogs-service, pull requests merged in 2021-09, with the labels that each got.

#1 docs(.example.env): add example path to connect postgres database
  .example.env
Labels: documentation

#2 Feature/listar todos os caes
  src/controllers/dogs/ListDogsController.ts
  src/controllers/dogs/index.ts
  src/controllers/index.ts
  src/routes/dogs.routes.ts
  src/routes/index.ts
  src/services/convertToBoolean.ts
  src/services/convertToContains.ts
  src/services/convertToNumber.ts
  src/services/index.ts
  src/services/presetQueryFields.ts
Labels: enhancement, good first issue

#3 Feature/integration with address search
  prisma/migrations/20210911185729_insert_data/migration.sql
  src/controllers/dogs/CreateDogController.ts
  src/controllers/dogs/ListDogsController.ts
  src/controllers/dogs/index.ts
  src/controllers/owners/CreateOwnerController.ts
  src/controllers/users/index.ts
  src/errors/missing-param-error.ts
  src/routes/dogs.routes.ts
  src/routes/owner.routes.ts
  yarn.lock
Labels: enhancement
